name: SlimeChem
authors: [Mooy1, Seggan, TheBusyBiscuit]
description: slimefun chemistry
main: io.github.mooy1.slimechem.SlimeChem
website: https://github.com/Mooy1/SlimeChem
depend: [Slimefun, CS-CoreLib]
softdepend: []
version: ${project.version}
api-version: 1.16
