name: SlimeChem
authors: [Mooy1, Seggan, TheBusyBiscuit]
description: slimefun chemistry
main: io.github.addoncommunity.slimechem.SlimeChem
depend: [Slimefun]
version: ${project.version}
api-version: 1.16
